<h1>DragonFly Editor - Editor</h1>
<?php
	#session_start();
	#$_SESSION['set']; <- itemSets des mecs qui ont uploadés
	
	#Ici commence la récupération
	define ("Original_Summoner_s_Rift", 1);
	define ("Twisted_Treeline", 10);
	define ("Summoner_s_Rift", 11);
	define ("Howling_Abyss", 12);
	
	
    $FR_item_list=file_get_contents('http://ddragon.leagueoflegends.com/cdn/5.2.1/data/en_US/item.json');
	$DecodedList = json_decode($FR_item_list, true);
	
	function display_Icon($ID, $classes=array("image_margin")){
		$display_classes = '';
		foreach ($classes as $class){
			$display_classes = $display_classes.' '.$class;
		}
		$image = '<img class="'.$display_classes.'" src="http://ddragon.leagueoflegends.com/cdn/5.2.1/img/item/'.$ID.'.png" alt="texte alternatif" />';
		echo $image;
	}
	
	function prepare_descriptions($item){
		//Ajouter l'ID dans les class pour les personaliser dans le CSS pour l'affichage
		$image = 'Leads to :<br/>';
		foreach ($item['into'] as $evolution){
			$image = $image.'<img class="hidden image_margin" src="http://ddragon.leagueoflegends.com/cdn/5.2.1/img/item/'.$evolution.'.png" alt="texte alternatif" />';
		}
		$display = '<div class="hidden item_description">'.$item['name'].'<br/>'.$item['description'].'<br/>'.$image.'<br/></div>';
		echo $display;
	}
	
	function display_all_selected($ItemsList, $Maps = array(), $Tags = array()){
		#If sur le nombre d'argument évidemment !
		#$MyLocalDecodedList = func_get_arg(0);
		#$criterias = func_get_args();
		//$currentItem = ID de l'item
		//$value = tableau des données de l'item. Les données sont soit des tableaux soit des tableaux associatifs. 
		//$value['donnée'][index ou clef]
		
		$TrueItemData = $ItemsList['data'];
		echo '<div class="items_zone">';
		foreach($TrueItemData as $currentItem => $value){
			$IsDisplayed = true;
			prepare_descriptions($value);
			$DescriptionArray[] = $value['description'];
			//We do not need non-purchasable items for now.
			if (!$value['gold']['purchasable']){
				$IsDisplayed = false;
			}	
			else{	
				if (isset($value['maps'])){ //first test if the object has a map field. If not it is displayed because it means it is on all the maps.
					if (!empty($Maps)){
						foreach($Maps as $NotPlayedMap){
							if(isset($value['maps'][$NotPlayedMap]) && !$value['maps'][$NotPlayedMap]){
								//echo "je passe et j'ignore : ".$value['name'].'<br/>';
								$IsDisplayed = false;
							}
						}
					}	
				}

				if (!empty($Tags)){
					$TagChoice = false;
					foreach($Tags as $chosenTag){
						if(!empty($value['tags']) && !$TagChoice){
							foreach($value['tags'] as $itemTag){
								if ($itemTag == $chosenTag){
									$TagChoice = true;
								}
							}
						}
					}
					if (!$TagChoice){
						$IsDisplayed = false;
					}
				}
				
				if ($IsDisplayed) {
					display_Icon($currentItem);
				}
			}
		}
		/*
		#$key contient les id
		#$value contient le tableau assoc de chaque item
		$key=
		$image = '<img src="http://ddragon.leagueoflegends.com/cdn/5.2.1/img/item/'.$key.'.png" alt="texte alternatif" />';
		$name = $value['name'];*/
		
	}
	$maps = array(Summoner_s_Rift, Original_Summoner_s_Rift);
	$tags = array('AttackSpeed');
	
	
	display_all_selected($DecodedList, $maps, $tags);

	
?>