<h1>DragonFly Editor - Editor</h1>
<body onload="page_loaded()" class = "EditorWindow">
<div class = "filters_zone">
<button class="SummonerRiftSelector" onclick="show_map(1)">Summoner's Rift</button>
<button class= "TwistedTreelineSelector" onclick="show_map(2)">Twisted Treeline</button>
<button class= "HowlingAbyssSelector" onclick="show_map(3)">Howling Abyss</button>
</div>
<?php
	#session_start();
	#$_SESSION['set']; <- itemSets des mecs qui ont uploadés
	
	#Ici commence la récupération
	define ("Original_Summoner_s_Rift", 1);
	define ("Twisted_Treeline", 10);
	define ("Summoner_s_Rift", 11);
	define ("Howling_Abyss", 12);
	
	
    $FR_item_list = file_get_contents('http://ddragon.leagueoflegends.com/cdn/5.2.1/data/en_US/item.json');
	$DecodedList = json_decode($FR_item_list, true);
	
	function display_Icon($ID, $classes=array("image_item")){
		//Pour l'affichage des items.
		$display_classes = '';
		foreach ($classes as $class){
			$display_classes = $class.' '.$display_classes;
		}
		$block = '<span id ="'.$ID.'" onclick="select('.$ID.')"><img class="'.$display_classes.'" onmouseover="show_description('.$ID.')" onmouseout="hide_description('.$ID.')" src="http://ddragon.leagueoflegends.com/cdn/5.2.1/img/item/'.$ID.'.png" alt="texte alternatif" /></span>';
		echo $block;
	}
	
	function prepare_descriptions($item, $id){
		//Pour l'affichage des descriptions des items.
		//Ajouter l'ID dans les class pour les personaliser dans le CSS pour l'affichage
		if (!empty($item['into']))
			$block = 'Leads to :<br/>';
		else
			$block = '';
		foreach ($item['into'] as $evolution){
			$block = $block.'<img class="image_description" src="http://ddragon.leagueoflegends.com/cdn/5.2.1/img/item/'.$evolution.'.png" alt="texte alternatif" />';
		}
		$display = '<div id="desc_'.$id.'" class="item_description">'.$item['name'].'<br/>'.$item['description'].'<br/>'.$block.'<br/></div>';
		$display_selected = '<div id="select_'.$id.'" class="selected_item_description">'.$item['name'].'<br/>'.$item['description'].'<br/>'.$block.'<br/></div>';
		echo $display;
		echo $display_selected;
	}
	
	function display_items($ItemsList, $Maps = array(), $Tags = array()){
		//$currentItem = ID of the item
		//$value = data tab of the item. Data are also tabs or key/value tabs. 
		//$value['data'][index/key]
		
		$TrueItemData = $ItemsList['data'];
		echo '<div class="items_zone">';
		foreach($TrueItemData as $currentItem => $value){
			$IsDisplayed = true;
			$classes = array("image_item");
			prepare_descriptions($value, $currentItem);
			$DescriptionArray[] = $value['description'];
			//We do not need non-purchasable items for now.
			if (!$value['gold']['purchasable']){
				$IsDisplayed = false;
			}	
			else{	
				if (isset($value['maps'])){ //first test if the object has a map field. If not it is displayed because it means it is on all the maps.
					foreach ($value['maps'] as $itemMaps => $bool){
						switch($itemMaps){
							case Original_Summoner_s_Rift : $classes[] = 'OriginalSummonersRift';
							break;
							case Twisted_Treeline : $classes[] = 'TwistedTreeline';
							break;
							case Summoner_s_Rift : $classes[] ='SummonersRift';
							break;
							case Howling_Abyss : $classes[] = 'HowlingAbyss';
							break;
						}
					}
					if (!empty($Maps)){
						foreach($Maps as $PlayedMap){
							if(isset($value['maps'][$PlayedMap]) && !$value['maps'][$PlayedMap]){
								//echo "je passe et j'ignore : ".$value['name'].'<br/>';
								$IsDisplayed = false;
							}
						}
					}	
				}
				if(!empty($value['tags'])){
					foreach($value['tags'] as $itemTag){
						$classes[] = $itemTag;
					}
				}
				display_Icon($currentItem, $classes);
			}
		}
		/*
		#$key contient les id
		#$value contient le tableau assoc de chaque item
		$key=
		$image = '<img src="http://ddragon.leagueoflegends.com/cdn/5.2.1/img/item/'.$key.'.png" alt="texte alternatif" />';
		$name = $value['name'];*/
		
	}
	$maps = array(Summoner_s_Rift, Original_Summoner_s_Rift);
	$tags = array('AttackSpeed');
	
	
	display_items($DecodedList, $maps);

	
?>
</body>