<h1>DragonFly Editor</h1>
<div class='subtitle'>
    The most important, powerful, trustworthy and friendly editor for League of Legends Item Sets !
</div>
<h3>To be brief...</h3>
<div class="message">
    One thing to note is that the development of such a project is very long and that it's still undergoing. So please, don't judge too harshly this work of ours. For the time being, we'll provide you an upload system, an editor and/or creator and our wonderful blank page with no way out (try it, it's worth it).
</div>
<div>
    <ul>
        <li><a href='/upload/index'>Upload system</a></li>
        <li><a href='/index/editor'>Editor</a></li>
        <li><a href='/index/blank'>The incredible, fabulous, marvelous and legendary Blank Page</a></li>
    </ul>
</div>