<!DOCTYPE html>
<html>
<head>
<title>DragonFly Editor website</title>
</head>

<body>
<?php
	#session_start();
	#$_SESSION['set']; <- itemSets des mecs qui ont uploadés
	
	#Ici commence la récupération
    $FR_item_list=file_get_contents('http://ddragon.leagueoflegends.com/cdn/5.2.1/data/fr_FR/item.json');
	$DecodedList = json_decode($FR_item_list, true);
	
	function display_all_selected(){
		 #If sur le nombre d'argument évidemment !
		$MyLocalDecodedList = func_get_arg(0);
		$TrueItemData = $MyLocalDecodedList['data'];

		$criterias = func_get_args();
		
		
		
		unset($criterias[0]);
		foreach($criterias as $key){
			foreach($TrueItemData as $currentItem => $value){
			if (isset ($value['maps'][$key])){
				echo 'L\'objet suivant n\'est pas sur la carte 10 : '.$value['name'];
				var_dump($test);
				var_dump($value['maps']);
				die;
			}
			else{
				$image = '<img src="http://ddragon.leagueoflegends.com/cdn/5.2.1/img/item/'.$currentItem.'.png" alt="texte alternatif" />';
				echo $image;
				}
				echo '<br/>';
			}
			
		}
		/*
		#$key contient les id
		#$value contient le tableau assoc de chaque item
		$key=
		$image = '<img src="http://ddragon.leagueoflegends.com/cdn/5.2.1/img/item/'.$key.'.png" alt="texte alternatif" />';
		$name = $value['name'];*/
		
	}
	#T'as laissé en plan ici, tu essaie de faire en sorte qu'un tableau puisse passer en argument de ta fonction et que seuls les items avec les maps sélectionnées dans le tableau, soient pris en compte
	$maps = array('10' => false, '12' => false);
	display_all_selected($DecodedList, 10);

	
?>
</body>

</html>