<form action='<?php echo $target;?>' method='POST' enctype="multipart/form-data">
    <input type='radio' name='type' value='properties' id='type_properties'/><label for='type_properties'>Properties file (from the air client)</label><br/>
    <input type='radio' name='type' value='custom' id='type_custom'/><label for='type_custom'>Custom file</label><br/>
    <input type='file' name='uploaded' id='uploaded'/><br/>
    <input type='submit' value='Send file'/>
</form>