<!DOCTYPE html>
<html>
    <head>
        <title>DragonFly Editor - Upload</title>
        <meta name="description" content="Upload system for the DragonFly Editor"/>
        <link rel="stylesheet" type="text/css" href="/css/upload.css"/>
        <script src="/js/jquery-2.1.4.min.js" type="text/javascript"></script>
        <script src="/js/upload.js" type="text/javascript"></script>
    </head>
    <h1>DragonFly Editor - Upload</h1>
    <body>
        <div class='formulaire_upload'>
            <form action='<?php echo $target;?>' method='POST' enctype="multipart/form-data">
                <input type='file' name='uploaded1' id='uploaded1' onChange='newUpload("uploaded1")' class='uploaded'/><br/>
                <input type='submit' value='Send file' class="submit_button"/>
            </form>
        </div>
    </body>
</html>